/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const LOAD_CAROUSEL_START = 'LOAD_CAROUSEL_START';
export const LOAD_CAROUSEL_SUCCESS = 'LOAD_CAROUSEL_SUCCESS';
export const LOAD_CAROUSEL_ERROR = 'LOAD_CAROUSEL_ERROR';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const USER_CREATE_START = 'USER_CREATE_START';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_CREATE_ERROR = 'USER_CREATE_ERROR';

export const COLLABORATOR_CREATE_START = 'COLLABORATOR_CREATE_START';
export const COLLABORATOR_CREATE_SUCCESS = 'COLLABORATOR_CREATE_SUCCESS';
export const COLLABORATOR_CREATE_ERROR = 'COLLABORATOR_CREATE_ERROR';